#!/usr/bin/env bash

################################################################################
# Check if password is compromised using pwnedpasswords.com                    #
# Password is hashed, than hash is split into prefix and suffix                #
# Prefix is used for searching mathing hashes                                  #
# Suffix is used for filtering the returned hashes                             #
# This script can be used in a pipe, or with a password as an argument         #
################################################################################

if [[ -z $1 ]]; then
  read -srp "Enter the password to check: " candidate_password
  if [[ ${candidate_password} == "" ]]; then
    printf "\nNo password provided\n"
    exit 1
  fi
else
  candidate_password=$1
fi

full_hash=$(printf "%s" "${candidate_password}" | sha1sum | awk '{print $1}')
prefix="${full_hash:0:5}"
suffix="${full_hash:5}"

curl -s "https://api.pwnedpasswords.com/range/${prefix}" \
  | grep -i "${suffix}" \
  && printf "Candidate password is compromised\n" \
  || printf "Candidate password is OK for use\n"
