#!/usr/bin/env bash

################################################################################
# Add tree-sitter parsers to path recognised by Neovim
# Requiremens:
#   sed
#   curl
################################################################################

function link_sitters {
	local sitter link_parent link

	for i in /usr/lib64/libtree-sitter-*; do
		if [[ ! -L $i ]]; then
			sitter=$(echo "$i" | sed -E 's|.*/libtree-sitter-||; s|\.so\..*|.so|')
			link_parent='/usr/lib64/nvim/parser/'
			link="$link_parent$sitter"
			if [[ ! -e $link || $i -nt $link ]]; then
				echo "linking $link to $i"
				ln -s "$i" "$link"
			else
				echo "$link exists"
			fi
		fi
	done
}

function download_scm {
	local langs lang_parent file_types file_ext url
	langs=('go' 'python' 'bash' 'json' 'javascript' 'html' 'css' 'elixir' 'java' 'make')
	file_types=('folds' 'highlights' 'indents' 'injections' 'locals')
	file_ext='.scm'
	lang_parent='/usr/share/nvim/runtime/queries/'
	url='https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/'

	for lang in "${langs[@]}"; do
		lang_path="$lang_parent""$lang"
		if [[ ! -e $lang_path ]]; then
			mkdir -p "$lang_path"
			chmod -R 755 "$lang_path"
		fi
		for file_type in "${file_types[@]}"; do
			file_name="$file_type$file_ext"
			curl "$url""$lang"/"$file_name" -o "$lang_path"/"$file_name"
		done
	done
}

function main {
	link_sitters
	download_scm
}

main
