#!/usr/bin/env bash

langs=(
        comment 
        bash awk python sql
        go zig cpp java rust
        make cmake nginx dockerfile
        json toml proto graphql
        html html_tags xml css 
        ecma javascript jsx typescript jsdoc 
)

function link_sitters {
	local sitter link_parent link
	for i in /usr/lib64/libtree-sitter-*; do
		if [[ ! -L $i ]]; then
			sitter=$(echo "$i" | sed -E 's|.*/libtree-sitter-||; s|\.so\..*|.so|')
			link_parent='/usr/lib64/nvim/parser/'
			link="$link_parent$sitter"
			if [[ ! -e $link || $i -nt $link ]]; then
				ln -s "$i" "$link"
			fi
		fi
	done
}

function download_ts_queries {
	local queries types url
	types=(folds highlights indents injections locals)
	queries="$HOME/.config/nvim/queries"
        if pushd "$queries" >/dev/null 2>&1; then
                for lang in "${langs[@]}"; do
                        lang_path="$queries"/"$lang"
                        if [[ ! -d $lang_path ]]; then
                                mkdir -p "$lang_path"
                                chmod -R 750 "$lang_path"
                        fi
                        if pushd "$lang" >/dev/null 2>&1; then
                                for type in "${types[@]}"; do
                                        url="https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/$lang/$type.scm"
                                        if curl "$url" --silent --head --fail >/dev/null 2>&1; then
                                                curl "$url" -s -L -O >/dev/null 2>&1
                                        fi
                                done
                                popd >/dev/null 2>&1 || continue
                        fi
                done
                popd >/dev/null 2>&1 || return
        fi
}

function main {
        if ! command -v curl >/dev/null 2>&1 \
        && ! command -v sed >/dev/null 2>&1; then
                exit 1
        fi
	# link_sitters
	download_ts_queries
}

main
