if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if ! [[ $PATH =~ $HOME/.local/bin:$HOME/bin: ]]; then
	PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

if ! shopt -oq posix; then
	. /usr/share/bash-completion/bash_completion
fi

. "$HOME/.bash_profile"
