set -g base-index 1
set -g focus-events on
set -g default-terminal tmux-256color
set -a terminal-features "xterm-256color:RGB"
set -a terminal-features "foot:RGB"
set -g status-style bg=terminal
set -g status-style fg=terminal
set -g status-style fill=terminal
set -g prefix C-a
setw -g mode-keys vi
setw -g pane-base-index 1
unbind C-b
unbind -T copy-mode-vi v
bind C-a send-prefix
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R
bind -T prefix a copy-mode \; send -X start-of-line
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind -T copy-mode-vi 'y' send -X copy-selection
bind p paste-buffer
